[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333f"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
port = 8501
enableXsrfProtection = false
